filepath_measurements_info: "/Volumes/cytokinesis-zebrafish-collab/magnetic_tweezers_time_prec/2_analysis/time_prec_phases_tweezers_info.csv"
dir_parent: "/Volumes/cytokinesis-zebrafish-collab/magnetic_tweezers_time_prec"
recalculate: True