filepath_measurements_info: "/Volumes/cytokinesis-zebrafish-collab/magnetic_tweezers_SD/2_analysis/sd_tweezers_info.csv"
dir_parent: "/Volumes/cytokinesis-zebrafish-collab/magnetic_tweezers_SD"

recalculate: True
subtract_background: True

save_to_server: True
plot: True

pix_size: 0.54 # (um)
dt: 0.5 # (s)