filepath_measurements_info: "/Volumes/cytokinesis-zebrafish-collab/magnetic_tweezers_SD/2_analysis/sd_tweezers_info.csv"
dir_parent: "/Volumes/cytokinesis-zebrafish-collab/magnetic_tweezers_SD"

recalculate: True
subtract_background: True

save_to_server: False
plot: True

force_ranges: [[20, 60]]  # (pN) force ranges for averaging curves

mt_codes: ['y', 'n']
conditions: ['Interphase', 'M-phase']
color_palette: 'tab10'

fit_type: 'full jeff' # other options: 'full jeff', 'full KV', 'creep jeff'

pix_size: 0.54 # (um)
dt: 0.5 # (s)